INSERT person  ( `fio`, `country`) VALUES('Абраменков Александр Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Агапов Александр Павлович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Аграновский А.В.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Аграновский Александр Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('АДЛЕР Марк','США');
INSERT person  ( `fio`, `country`) VALUES('Акатьев Дмитрий Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Алимов Николай Иванович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Алимурадов Алан Казанферович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Алиханов Адиль Хакимович','Россия');
INSERT person  ( `fio`, `country`) VALUES('АЛЛЕН Молли','США');
INSERT person  ( `fio`, `country`) VALUES('Алперин Евгений Данилович','Россия');
INSERT person  ( `fio`, `country`) VALUES('АМЕЛЬ Филипп','Франция');
INSERT person  ( `fio`, `country`) VALUES('Андреев Михаил Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Андрианов В.В.','Россия');

INSERT person  ( `fio`, `country`) VALUES('Андрианов Владимир Васильевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Армер Андрей Игоревич','Россия');
INSERT person  ( `fio`, `country`) VALUES('АРНДТ ДР ХАБИЛ Кристоф','Германия');
INSERT person  ( `fio`, `country`) VALUES('Арутюнян Роман Эрнстович','Россия');
INSERT person  ( `fio`, `country`) VALUES('АСЕРО Алехандро','США');
INSERT person  ( `fio`, `country`) VALUES('Асташов Роман Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Афанасьев Андрей Алексеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('АХН Дзае Хонг','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('БАЗАНОВ Петр Валерьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('БАК Еун-санг','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('Баклаев Александр Вадимович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Балакин Александр Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Баранников Вячеслав А.','Россия');
INSERT person  ( `fio`, `country`) VALUES('БАРТОЛОМЬЮ Сьюзан','США');
INSERT person  ( `fio`, `country`) VALUES('Баря Елена Андреевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Басов Олег Олегович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Батальщиков Александр Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Батенков Кирилл Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Белиловский Виктор Абрамович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Беллавин Михаил Сергеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Белов Александр Сергеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Белов Сергей Павлович','Россия');
INSERT person  ( `fio`, `country`) VALUES('БЕННИ Брайан','США');
INSERT person  ( `fio`, `country`) VALUES('Бинеев Осман Рифатович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Бобров Николай Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Бова Виктория Викторовна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Бойков Илья Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Болдышев Алексей Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Борисенко Николай Павлович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Бочаров Николай Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Бочкарев В.Л.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Бочкарев И.В.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Бочкарев Игорь Вячеславович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Бочкарев С.Л.','Россия');

INSERT person  ( `fio`, `country`) VALUES('Бочкарев Сергей Львович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Брайнина И.С.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Брайнина Ирина Соломоновна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Будков Виктор Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Бузурнюк Николай Степанович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Булгаков Олег Митрофанович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Булушева Анна Владимировна','Россия');
INSERT person  ( `fio`, `country`) VALUES('БУНЧУХ Брюс','США');
INSERT person  ( `fio`, `country`) VALUES('Бураков Сергей Васильевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('БУРЯК Дмитрий Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ВАН Вэй То Вильям','Китай');
INSERT person  ( `fio`, `country`) VALUES('ВАН Е-И','США');
INSERT person  ( `fio`, `country`) VALUES('ВАН Куаньсань','США');
INSERT person  ( `fio`, `country`) VALUES('ВАНГ Куансан','США');
INSERT person  ( `fio`, `country`) VALUES('Верходанова Василиса Олеговна','Россия');
INSERT person  ( `fio`, `country`) VALUES('ВИ Деннис Чи Вай','Китай');
INSERT person  ( `fio`, `country`) VALUES('Витязев Владимир Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ВЛАСЮК Эугениуш','Польша');
INSERT person  ( `fio`, `country`) VALUES('Волченков Владимир Андреевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ВОН Сунг-Дзоон','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ВУ Тао','США');
INSERT person  ( `fio`, `country`) VALUES('Гаджиев Махач Хайрудинович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Гармонов Александр Васильевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ГАРУДАДРИ Харинат','США');
INSERT person  ( `fio`, `country`) VALUES('Гасанова Татьяна Олеговна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Гельфенбейн Илья Геннадьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Гельфенбейн Ольга Александровна','Россия');
INSERT person  ( `fio`, `country`) VALUES('ГЕРТЗ Майкл','США');
INSERT person  ( `fio`, `country`) VALUES('Гефке Денис Алексеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Гиголо Людмила Антоновна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Главатских Игорь Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Глухов Дмитрий Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Гмарь Дмитрий Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Голубинский Андрей Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Гончарук Артем Владимирович','США');
INSERT person  ( `fio`, `country`) VALUES('Гордеев Денис Игоревич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Грабов Евгений Йосифович','Украина');
INSERT person  ( `fio`, `country`) VALUES('Григорьева Юлия Сергеевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Григорян Рубен Левонович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Гриняк Виктор Михайлович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ГУН Ифань','США');
INSERT person  ( `fio`, `country`) VALUES('ГУО Йонг','США');
INSERT person  ( `fio`, `country`) VALUES('Гусев Михаил Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ГУССЕН Уве','Германия');
INSERT person  ( `fio`, `country`) VALUES('Гущина Анастасия Александровна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Данилов Александр Геннадьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Дворянкин Сергей Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Дегтярев Владимир Михайлович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Демин Евгений Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ДЕН АУДЕН Арт','Бельгия');
INSERT person  ( `fio`, `country`) VALUES('ДЕНГ Ли','США');
INSERT person  ( `fio`, `country`) VALUES('ДЖАКОБИ Джеймс Д.','США');
INSERT person  ( `fio`, `country`) VALUES('ДЖИАЙМО III Эдвард К.','США');
INSERT person  ( `fio`, `country`) VALUES('ДЗУ Юн-Ченг','США');
INSERT person  ( `fio`, `country`) VALUES('ДЗУНГ Дзае-воок','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ДОНАЛЬДСОН Томас Алан','Великобритания');
INSERT person  ( `fio`, `country`) VALUES('ДРОППО Джеймс Г.','США');
INSERT person  ( `fio`, `country`) VALUES('ДРОППО Джеймс Дж.','США');
INSERT person  ( `fio`, `country`) VALUES('Дубовицкий Николай Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ДУНИ Этан Роберт','США');
INSERT person  ( `fio`, `country`) VALUES('Дырмовский Дмитрий Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ДЭВИС Лео','США');
INSERT person  ( `fio`, `country`) VALUES('Евмененко Антон Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Ермолаев А.А.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Ермолаев Алексей Алексеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Есакова Марина Игоревна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Жарков Игорь Вениаминович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Жданов А.Б.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Жданов Андрей Борисович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Железняк Владимир Кириллович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Желтов Павел Валерьянович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Жидков Сергей Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Жиляков Евгений Георгиевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Жуков Роман Алексеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Запорожец Дмитрий Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Затворницкий Александр Петрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Зацепин Павел Михайлович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Зулкарнеев Михаил Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ЗХАНГ Зхенгиоу','США');
INSERT person  ( `fio`, `country`) VALUES('Зыков Александр Павлович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Иванов А.И.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Иванов Владимир Алексеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Иванов Иван Иванович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Иванов Илья Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Иванов Николай Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Иванов Сергей Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Иванченко Александр Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Иванько Денис Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ИГАРАСИ Хисаказу','США');
INSERT person  ( `fio`, `country`) VALUES('Игнатов Дмитрий Олегович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Илюшин Михаил Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Истратов Виктор Алексеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ЙООН Сеунг-ил','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ЙОХАНССОН Ингемар','Швеция');
INSERT person  ( `fio`, `country`) VALUES('Калашников Дмитрий Михайлович','Россия');
INSERT person  ( `fio`, `country`) VALUES('КАЛИНИНА Елена Андреевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Калмыков Алексей Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('КАМПЕР Шарль','Бельгия');
INSERT person  ( `fio`, `country`) VALUES('Караульных Денис Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Карпов Алексей Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Карпов Николай Вячеславович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Касымова Эльвира Исмаиловна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Катанович Андрей Андреевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('КВОН Ох-юн','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('КЕЛЬБА Чиприан И.','США');
INSERT person  ( `fio`, `country`) VALUES('КЕННЕДИ Пол А.','США');
INSERT person  ( `fio`, `country`) VALUES('Кибкало Александр А.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кибкало Александр Алексеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('КИМ Дзае-чеол','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('КИМ Дзунг-Хое','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('КИМ До-ван','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('КИМ Ки-сук','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('КИМ Миунг-дзае','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('Кипяткова Ирина Сергеевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('КИСС Имре','Финляндия');
INSERT person  ( `fio`, `country`) VALUES('КИШШ Имре','Финляндия');
INSERT person  ( `fio`, `country`) VALUES('Клевлеев Степан Андреевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кнеллер Эммануил Григорьевич','Россия');

INSERT person  ( `fio`, `country`) VALUES('Кнох Владимир Яковлевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('КО Шиюнь-цзу','США');
INSERT person  ( `fio`, `country`) VALUES('Коваль С.Л.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Коваль Сергей Львович','Россия');

INSERT person  ( `fio`, `country`) VALUES('Козин Дмитрий Валерьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Колоколов Александр Сергеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Колосов Андрей Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Комелягин Алексей Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Комиссаров Анатолий Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Комиссарова Ольга Анатольевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Конюхов Павел Вячеславович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кореневский Максим Львович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Корнаухов Михаил Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Котов Михаил Андреевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Котомин Сергей Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кочаров Даниил Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кравченко Юрий Алексеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Краснов Василий Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Крашенинников Виктор Ростиславович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кротенок Ксения Игоревна','Россия');
INSERT person  ( `fio`, `country`) VALUES('КРУМЕЛ Эндрю К.','США');
INSERT person  ( `fio`, `country`) VALUES('Кручинин Александр Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кудаков Константин Евгеньевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кудинов Михаил Сергеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кузнецов Денис Павлович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кузнецов М.В.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кузнецов Михаил Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кулешов Павел Евгеньевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('КУНЦМАНН Зигфрид','Германия');
INSERT person  ( `fio`, `country`) VALUES('Курейчик Владимир Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Курлов Александр Васильевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кучукова Наталья Николаевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Кушнир Дмитрий Алексеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Лабо Дмитрий Сергеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Лабутин П.В.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Лабутин Павел Вадимович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Ле Ман Ха','Россия');
INSERT person  ( `fio`, `country`) VALUES('Лебедев Константин Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ЛЕВИТ Майкл','США');
INSERT person  ( `fio`, `country`) VALUES('Леднов Д.А.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Леднов Дмитрий Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ЛЕЖЕ Франсуа','Бельгия');
INSERT person  ( `fio`, `country`) VALUES('Лежебоков Андрей Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ЛЕППЯНЕН Юсси Арттури','Финляндия');
INSERT person  ( `fio`, `country`) VALUES('ЛЕУНГ Хун Чунг','Китай');
INSERT person  ( `fio`, `country`) VALUES('ЛИ Дзоо-йеонг','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ЛИ Чжун Юа','США');
INSERT person  ( `fio`, `country`) VALUES('ЛИ Чин Вай Джимми','Китай');
INSERT person  ( `fio`, `country`) VALUES('ЛИ Юи-йоон','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ЛИ Юнг Джин','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ЛИБЕРМАН Амир','Израиль');
INSERT person  ( `fio`, `country`) VALUES('ЛИДТКЕ Клаус-Дитер','Германия');
INSERT person  ( `fio`, `country`) VALUES('ЛИКЕ Пьер-Сильван','Франция');
INSERT person  ( `fio`, `country`) VALUES('Липсюк Василий Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Липчанский Антон Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ЛИУ Зиченг','США');
INSERT person  ( `fio`, `country`) VALUES('Лобанова Марина Анатольевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Лобов Владимир Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Лотков Михаил Михайлович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Лтд.','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ЛЮ Цзычэн','США');
INSERT person  ( `fio`, `country`) VALUES('ЛЮ Ю','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ЛЯНЬ Хонгин','США');
INSERT person  ( `fio`, `country`) VALUES('Ляхов Павел Рудольфович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Маковкин Константин Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Максимов Дмитрий Андреевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('МАРКЕФКА Гунтберт','Германия');
INSERT person  ( `fio`, `country`) VALUES('МАССЕ Пьер-Александр Ф.','США');
INSERT person  ( `fio`, `country`) VALUES('МАХАДЖАН Милинд В.','США');
INSERT person  ( `fio`, `country`) VALUES('Меджидов Мухтар Муртузалиевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Мельников Сергей Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Меренков Антон Сергеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Меркулов Максим Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('МЕРРИЛЛ Джон','США');
INSERT person  ( `fio`, `country`) VALUES('МИВА Таро','США');
INSERT person  ( `fio`, `country`) VALUES('МИЛЛЕР Томас Ли','США');
INSERT person  ( `fio`, `country`) VALUES('Миняев Андрей Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Мирошниченко Владимир Витальевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Митыпов Марат Мирсапович','Россия');
INSERT person  ( `fio`, `country`) VALUES('МИЦУЕСИ Синдзи','Япония');
INSERT person  ( `fio`, `country`) VALUES('МОВАТТ Давид','США');
INSERT person  ( `fio`, `country`) VALUES('МОВАТТ Дэвид','США');
INSERT person  ( `fio`, `country`) VALUES('Можин Сергей Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Музычка Степан Андреевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('МУН Ван Джин','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('МУРТХИ Рагху','США');
INSERT person  ( `fio`, `country`) VALUES('МУРЫНИН Александр Борисович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Мызников Борис Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Мышкин Александр Сергеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Мясоедова Зинаида Павловна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Назарова Татьяна Владимировна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Наздратенко Андрей Евгеньевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Настасенко Марина Валерьевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Насыпный Владимир Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Нгуен Виет Фан','Россия');
INSERT person  ( `fio`, `country`) VALUES('Недобыльский Андрей Олегович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Нигматуллин Руслан Рафикович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Низиенко Юрий Константинович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Николаенко Юрий Кимович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Николаенков Юрий Кимович','Россия');
INSERT person  ( `fio`, `country`) VALUES('НОРКРОСС Скотт Грегори','США');
INSERT person  ( `fio`, `country`) VALUES('Овсянникова Анна Сергеевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Огарок Андрей Леонтиевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ОДРЕН Жан-Поль','Франция');
INSERT person  ( `fio`, `country`) VALUES('ОЕРДЕР Мартин','Германия');
INSERT person  ( `fio`, `country`) VALUES('ОЛЬСЕН Еспер','Финляндия');
INSERT person  ( `fio`, `country`) VALUES('Орлова Мария Викторовна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Осочкин Александр Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Оськин В.А.','Россия');
INSERT person  ( `fio`, `country`) VALUES('ОХ Еун Ми','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ОХИАМА Хидеки','США');
INSERT person  ( `fio`, `country`) VALUES('Павлова Марианна Иосифовна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Панков Роман Егорович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Панкратов Игорь Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Панфилов Илья Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Панфилов Сергей Станиславович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Панфилова Марина Алексеевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('ПАРК Гео-геун','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ПАРК Дзоунг Киоу','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ПАРК Санг-шин','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ПАРК Сунг-воо','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('Петров Максим Андреевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Петров Олег Евгеньевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Петухова Hина Васильевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Петухова Нина Васильевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Пеховский Тимур Сахиевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Пилкин Виталий Евгеньевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Пимонов Андрей Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Пионтковская Ирина Игоревна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Пискунов Александр Дмитриевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Платонов Владимир Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Платонов Илья Андреевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ПОЛИФРОНИ Джозеф','США');
INSERT person  ( `fio`, `country`) VALUES('Полищук Станислав Васильевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Полков Анатолий Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Полков Андрей Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Попов Сергей Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ПОПП Харальд','Германия');
INSERT person  ( `fio`, `country`) VALUES('ПОРТЕР Марк Эдвард','США');
INSERT person  ( `fio`, `country`) VALUES('Потапенко А.М.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Потапов Всеволод Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Потапова Родмонга Кондратьевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('ПОТТЕР Дуглас У.','США');
INSERT person  ( `fio`, `country`) VALUES('Прибытков Юрий Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Присяч Татьяна Николаевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Прохоренко Екатерина Ивановна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Прудников Алексей Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ПУНДЖ Арун','США');
INSERT person  ( `fio`, `country`) VALUES('ПУРНАССЕХ Хоуман','США');
INSERT person  ( `fio`, `country`) VALUES('РАДЖЕНДРАН Вивек','США');
INSERT person  ( `fio`, `country`) VALUES('Раев А.Н.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Раев Андрей Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('РАЙДМИЛЛЕР Джеффри','США');
INSERT person  ( `fio`, `country`) VALUES('РАСМУССЕН Дэвид Джон','США');
INSERT person  ( `fio`, `country`) VALUES('Рассолов Владимир Сергеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('РЕДЕН Карл Йонас','Швеция');
INSERT person  ( `fio`, `country`) VALUES('Репалов С.А.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Репалов Сергей Анатолиевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Репалов Сергей Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('РЕТТИГ Бьорн К.','США');
INSERT person  ( `fio`, `country`) VALUES('РИДДЕРБУШ Фалько','Германия');
INSERT person  ( `fio`, `country`) VALUES('РИЧАРДСОН Бриджит Фрэнсис Мора','США');
INSERT person  ( `fio`, `country`) VALUES('Рогожкин Игнат Геннадьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Розов Валерий Иванович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Романенко Александр Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Ронжин Александр Леонидович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Ронжин Андрей Леонидович','Россия');
INSERT person  ( `fio`, `country`) VALUES('РУФФ Джозеф А.','США');
INSERT person  ( `fio`, `country`) VALUES('РУФФ Дзозеф А.','США');
INSERT person  ( `fio`, `country`) VALUES('Рыболовлев Александр Аркадьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Рыжачкин Иван П.','Россия');
INSERT person  ( `fio`, `country`) VALUES('РЭМСИ Уилльям Д.','США');
INSERT person  ( `fio`, `country`) VALUES('Рюмин Дмитрий Александрович','Казахстан');
INSERT person  ( `fio`, `country`) VALUES('Савинков Андрей Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Савченко Андрей Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Савченко Владимир Васильевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Савченко Людмила Васильевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Сазанов Виктор Васильевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Саитов Игорь Акрамович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Саруханов Ваган Арменович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Сахаров Виталий Олегович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Сборщиков Валерий Владимирович','Россия');

INSERT person  ( `fio`, `country`) VALUES('СВЕДБЕРГ Йонас','Швеция');
INSERT person  ( `fio`, `country`) VALUES('Селиховкин Иван Андреевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Семенкин Евгений Станиславович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Семенов Владимир Ильич','Россия');
INSERT person  ( `fio`, `country`) VALUES('СЕНДЗУ Казухиро','США');
INSERT person  ( `fio`, `country`) VALUES('СЕОЛ Гиунг Чан','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('Сергиенко Роман Борисович','Россия');
INSERT person  ( `fio`, `country`) VALUES('СИНКЛЭР Майкл Дж.','США');
INSERT person  ( `fio`, `country`) VALUES('Сиротин Павел Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Скачков Александр Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Скороходов Сергей Игоревич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Слепцов Тимофей Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Смехун Яна Альбертовна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Смирнов Валентин Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Снопко Сергей Игоревич','Россия');
INSERT person  ( `fio`, `country`) VALUES('СОЗАКАИ Макото','Бельгия');
INSERT person  ( `fio`, `country`) VALUES('Соколова Анастасия Владимировна','Россия');
INSERT person  ( `fio`, `country`) VALUES('СОН Хае-рим','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('Сопов Евгений Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Соснов Максим Евгеньевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Стародубцев Петр Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Стародубцев Юрий Иванович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Степаненкова Татьяна Евгеньевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Столов Евгений Львович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Струценко Алла Анатольевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Студёнова Дарья Вячеславовна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Субботина Наталия Александровна','Россия');
INSERT person  ( `fio`, `country`) VALUES('СУБРАМАНИА Амарнаг','США');
INSERT person  ( `fio`, `country`) VALUES('СУВАНАСУК Реркбоон','США');
INSERT person  ( `fio`, `country`) VALUES('Суворов Дмитрий Андреевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Суворов Олег Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Сулима П.М.','Россия');
INSERT person  ( `fio`, `country`) VALUES('СУРЕШ Мамата','США');
INSERT person  ( `fio`, `country`) VALUES('Суслов Сергей Валерьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Сухорукова Елена Валерьевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Сысоев Владимир Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Тампель Иван Борисович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Татарникова Марина Юрьевна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Ташлинский Александр Григорьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Телеснин Борис Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Телеснин Константин Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Тетерюков Дмитрий Олегович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Титов Олег Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Ткаченко Mаксим Сергеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Толстых Геннадий Дмитриевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Торбьерн В. СЕЛЬВЕ','США');
INSERT person  ( `fio`, `country`) VALUES('Треножкин Виктор Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Турин Владимир Сергеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Туровец Александр Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Тычков Александр Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('У Цян','США');
INSERT person  ( `fio`, `country`) VALUES('УВЛИДЕН Андерс','Швеция');
INSERT person  ( `fio`, `country`) VALUES('УЛЕ Кристиан','Германия');
INSERT person  ( `fio`, `country`) VALUES('Уманский Станислав Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('УОТКИНС Скотт Алан','США');
INSERT person  ( `fio`, `country`) VALUES('Ушаков Алексей Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ФАЛКЕНА Ян Рулоф','США');
INSERT person  ( `fio`, `country`) VALUES('Фарафонов Павел Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Фархадов Maис Паша оглы','Россия');
INSERT person  ( `fio`, `country`) VALUES('Фархадов Маис Паша оглы','Россия');
INSERT person  ( `fio`, `country`) VALUES('Федосов Михаил Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Федюкин Михаил Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ФЕЙГ Кевин Э.','США');
INSERT person  ( `fio`, `country`) VALUES('ФИЛЛИПС Майкл','США');
INSERT person  ( `fio`, `country`) VALUES('Фирсова Александра Александровна','Россия');
INSERT person  ( `fio`, `country`) VALUES('ФИШЕР Крейг М.','США');
INSERT person  ( `fio`, `country`) VALUES('Фомин Владимир Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ФОРО Эрик','Франция');
INSERT person  ( `fio`, `country`) VALUES('Хазимов Ян Тагирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ХАЙН Эккехард','Германия');
INSERT person  ( `fio`, `country`) VALUES('ХАРТ МЛ. Эдвард К.','США');
INSERT person  ( `fio`, `country`) VALUES('Хацкевич Андрей Валентинович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ХЕО Хие-хиун','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ХЕРРЕ Юрген','Германия');
INSERT person  ( `fio`, `country`) VALUES('Хилал Надежда Риядовна','Россия');
INSERT person  ( `fio`, `country`) VALUES('ХИЛЛ Питер Д.','США');
INSERT person  ( `fio`, `country`) VALUES('Хитина Марина Викторовна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Хитров Михаил Васильевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ХОЛБОСТЭД Мэри','США');
INSERT person  ( `fio`, `country`) VALUES('Хомяков Александр Борисович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ХОН Хсиао-Вуен','США');
INSERT person  ( `fio`, `country`) VALUES('ХОНЬ Сяо-Уэнь','США');
INSERT person  ( `fio`, `country`) VALUES('Хохлов Юрий Юрьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ХУАНГ Ксуедонг Д.','США');
INSERT person  ( `fio`, `country`) VALUES('ХУАНГ Сюэдун Дэвид','США');
INSERT person  ( `fio`, `country`) VALUES('Хуртилов Владислав Олегович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Хусаинов Айдар Фаилович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ХЬЮБЕР Ричард Е.','США');
INSERT person  ( `fio`, `country`) VALUES('ЦЗАН Сиаофен','США');
INSERT person  ( `fio`, `country`) VALUES('ЦЗЭН Синьчауань','США');
INSERT person  ( `fio`, `country`) VALUES('ЦЗЮЙ Юй-Чэн','США');
INSERT person  ( `fio`, `country`) VALUES('ЧА Тае-хван','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ЧАМБЕРС Роберт Л.','США');
INSERT person  ( `fio`, `country`) VALUES('ЧАН Шуанюй','США');
INSERT person  ( `fio`, `country`) VALUES('Черных Ирина Александровна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Чернышов Павел Валерьевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ЧЖАН Чженью','США');
INSERT person  ( `fio`, `country`) VALUES('ЧИН Сео Йонг','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ЧИТРАПУ Арун','США');
INSERT person  ( `fio`, `country`) VALUES('ЧИУ Чи Фай','Китай');
INSERT person  ( `fio`, `country`) VALUES('ЧО Сунг-кил','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ЧОО Ки Хиун','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ЧУН Киунг Дзоон','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('ЧУН Хинг Фай Луис','Китай');
INSERT person  ( `fio`, `country`) VALUES('Чупахин Павел Анатольевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Чураков Петр Павлович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Чучупал Владимир Яковлевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Шамраев Николай Георгиевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Шапранов Владимир Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Шаталов Эдуард Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ШАФФЕР Жольт','Нидерланды');
INSERT person  ( `fio`, `country`) VALUES('ШЕПЕРД Джозеф','США');
INSERT person  ( `fio`, `country`) VALUES('ШЕПЕРД Джон','США');
INSERT person  ( `fio`, `country`) VALUES('Шилов Вадим Владимирович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Широкова Анна Михайловна','Россия');
INSERT person  ( `fio`, `country`) VALUES('Шитьковский Виктор Викторович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ШМИД Патрисия М.','США');
INSERT person  ( `fio`, `country`) VALUES('Шмунк Дмитрий В.','Россия');
INSERT person  ( `fio`, `country`) VALUES('ШОЛЬЦ Оливер','США');
INSERT person  ( `fio`, `country`) VALUES('Штанчаев Хайрутин Баширович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ШТЕФАН Фредерик','Германия');
INSERT person  ( `fio`, `country`) VALUES('Шулипа Андрей Константинович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Эдель Дмитрий Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('ЭКУДДЕН Эрик','Швеция');
INSERT person  ( `fio`, `country`) VALUES('ЭМАМ Оссама','Египет');
INSERT person  ( `fio`, `country`) VALUES('ЭНДРЮ Феликс Дж. Т.И.','США');
INSERT person  ( `fio`, `country`) VALUES('ЮЙ Дун','США');
INSERT person  ( `fio`, `country`) VALUES('Юрьев Д.Н.','Россия');
INSERT person  ( `fio`, `country`) VALUES('Юрьев Дмитрий Николаевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('Ягупов Владимир Александрович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Яковлев Вадим Лаврович','Россия');
INSERT person  ( `fio`, `country`) VALUES('Ямшинин Александр Алексеевич','Россия');
INSERT person  ( `fio`, `country`) VALUES('ЯНГ Хае Кванг','Республика Корея');
INSERT person  ( `fio`, `country`) VALUES('Яцко Вячеслав Александрович','Россия');

