-- MySQL Script generated by MySQL Workbench
-- Sun Oct  1 20:31:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tech_data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tech_data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tech_data` DEFAULT CHARACTER SET utf8 ;
USE `tech_data` ;

-- -----------------------------------------------------
-- Table `tech_data`.`patent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `inid_12` VARCHAR(45) NULL COMMENT 'Cловесное обозначение вида документа',
  `inid_13` VARCHAR(45) NULL COMMENT 'Код вида документа',
  `inid_19` VARCHAR(45) NULL COMMENT 'Код страны публикации',
  `inid_24` DATE NULL COMMENT 'Дата приоритета или дата, с которой начинается действие прав промышленной собственности (дата начала отсчета срока действия патента)',
  `inid_33` VARCHAR(45) NULL COMMENT 'Страна приоритета',
  `inid_41` DATE NULL COMMENT 'Дата предоставления для всеобщего ознакомления не прошедшего экспертизу документа',
  `inid_43` DATE NULL COMMENT 'Дата публикации заявки',
  `inid_45` DATE NULL COMMENT 'Опубликовано',
  `inid_46` DATE NULL COMMENT 'Дата публикации формулы изобретения',
  `inid_54` VARCHAR(200) NULL COMMENT 'Название изобретения',
  `inid_85` DATE NULL COMMENT 'Дата начала рассмотрения заявки РСТ на национальной фазе',
  `inid_86_nuber` VARCHAR(45) NULL COMMENT 'Регистрационный номер заявки РСТ (Европейское патентное ведомство)',
  `inid_86_date` DATE NULL COMMENT 'Дата подачи заявки РСТ (Европейское патентное ведомство)',
  `inid_87_number` VARCHAR(45) NULL COMMENT 'Регистрационный номер публикации заявки РСТ',
  `inid_87_date` DATE NULL COMMENT 'Дата публикации заявки РСТ',
  `f_98` VARCHAR(230) NULL COMMENT 'Адрес для переписки',
  `f_121` VARCHAR(2083) NULL COMMENT 'Ссылка на реестр(заявка/патент) прим. 11_href',
  `f_122` VARCHAR(2083) NULL COMMENT 'Ссылка на реестр(заявка) прим. 21_href',
  `f_123` VARCHAR(2083) NULL COMMENT 'Официальная публикация заявки патента в формате PDF(ссылка) прим. 43_href',
  `f_124` VARCHAR(2083) NULL COMMENT 'Официальная публикация патента в формате PDF(ссылка)  прим. 45_href',
  `type` VARCHAR(45) NULL COMMENT 'тип документа: Заявка/Патент',
  PRIMARY KEY (`inid_11`),
  UNIQUE INDEX `inid_11_UNIQUE` (`inid_11` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = 'Патенты и заявки';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_inid_21`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_inid_21` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `inid_21` VARCHAR(45) NULL COMMENT 'Регистрационный номер заявки, включая номера присоединенных заявок',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_21_patent1_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_inid_21_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Регистрационный номер заявки, включая номера присоединенных заявок';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_inid_15`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_inid_15` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `inid_15` VARCHAR(1000) NULL COMMENT ' Информация о коррекции патента',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_15_patent1_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_inid_15_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = ' Информация о коррекции патента';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_inid_22`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_inid_22` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `inid_22` DATE NULL COMMENT 'Дата подачи заявки',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_22_patent1_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_inid_22_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Дата подачи заявки';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_inid_23`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_inid_23` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `inid_23` DATE NULL COMMENT 'Дата поступления дополнительных материалов к ранее поданной заявке',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_23_patent1_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_inid_23_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Дата поступления дополнительных материалов к ранее поданной заявке';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_inid_31`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_inid_31` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `inid_31` VARCHAR(45) NULL COMMENT 'Номер конвенционной заявки',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_31_patent1_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_inid_31_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Номер конвенционной заявки';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_inid_32`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_inid_32` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `inid_32` DATE NULL COMMENT 'Дата подачи конвенционной заявки ',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_32_patent1_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_inid_32_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Дата подачи конвенционной заявки ';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_inid_51`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_inid_51` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `inid_51` VARCHAR(45) NULL COMMENT 'Индексы международной патентной классификации изобретений (МПК) (Основной  индекс МПК/Дополнительные индексы МПК/Номер редакции МПК)',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_51_patent1_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_inid_51_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Индексы международной патентной классификации изобретений (МПК) (Основной  индекс МПК/Дополнительные индексы МПК/Номер редакции МПК)';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_inid_56`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_inid_56` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `inid_56` VARCHAR(45) NULL COMMENT 'Список источников информации, принятых во внимание при составлении заявки',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_56_patent1_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_inid_56_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Список источников информации, принятых во внимание при составлении заявки';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_inid_71`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_inid_71` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `s_name` VARCHAR(45) NULL COMMENT 'Заявитель.Фамилия.',
  `name` VARCHAR(45) NULL COMMENT 'Заявитель.Имя',
  `f_name` VARCHAR(45) NULL COMMENT 'Заявитель.Отчество.',
  `FIO_full` VARCHAR(200) NULL COMMENT 'Заявитель. ФИО полностью.',
  `FIO_initials` VARCHAR(45) NULL COMMENT 'Заявитель.Фамилия+инициалы',
  `FIO_as_is` VARCHAR(45) NULL COMMENT 'Заявитель.ФИО как приведено в источнике данных',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_71_patent1_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_inid_71_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Заявитель';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_inid_73`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_inid_73` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `s_name` VARCHAR(45) NULL COMMENT 'Патентообладатель.Фамилия.',
  `name` VARCHAR(45) NULL COMMENT 'Патентообладатель.Имя',
  `f_name` VARCHAR(45) NULL COMMENT 'Патентообладатель.Отчество.',
  `FIO_full` VARCHAR(200) NULL COMMENT 'Патентообладатель.ФИО полностью.',
  `FIO_initials` VARCHAR(45) NULL COMMENT 'Патентообладатель.Фамилия+инициалы',
  `FIO_as_is` VARCHAR(45) NULL COMMENT 'Патентообладатель.ФИО как приведено в источнике данных',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_73_patent1_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_inid_73_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Патентообладатель.';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_inid_74`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_inid_74` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `s_name` VARCHAR(45) NULL COMMENT 'Патентный поверенный. Фамилия.',
  `name` VARCHAR(45) NULL COMMENT 'Патентный поверенный. Имя',
  `f_name` VARCHAR(45) NULL COMMENT 'Патентный поверенный. Отчество.',
  `FIO_full` VARCHAR(200) NULL COMMENT 'Патентный поверенный. ФИО полностью.',
  `FIO_initials` VARCHAR(45) NULL COMMENT 'Патентный поверенный. Фамилия+инициалы',
  `FIO_as_is` VARCHAR(45) NULL COMMENT 'Патентный поверенный. ФИО как приведено в источнике данных',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_74_patent1_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_inid_74_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Патентный поверенный.';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_f125`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_f125` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `f_125` TEXT(1000) NULL COMMENT 'Извещение об изменениях сведений',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_31_patent10_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_patent_f125_patent1`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Извещение об изменениях сведений';


-- -----------------------------------------------------
-- Table `tech_data`.`patent_f126`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tech_data`.`patent_f126` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inid_11` VARCHAR(45) NOT NULL COMMENT 'Номер документа',
  `f_125` VARCHAR(2083) NULL COMMENT 'Извещение об изменениях сведений в формате PDF(ссылка)',
  PRIMARY KEY (`id`),
  INDEX `fk_patent_inid_31_patent10_idx` (`inid_11` ASC),
  CONSTRAINT `fk_patent_patent_f125_patent10`
    FOREIGN KEY (`inid_11`)
    REFERENCES `tech_data`.`patent` (`inid_11`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Извещение об изменениях сведений в формате PDF(ссылка)';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
